#!/bin/bash

echo -e "================================================="
echo -e "WELCOME TO IEPH DEVELOPERS SCRIPT"
echo -e ""  
echo -e "> menu         : Menu list"
echo -e "> usernew      : New user SSH"
echo -e "> trial        : Trial Account"
echo -e "> delete       : Delete Account"
echo -e "> check        : Check User Login"
echo -e "> member       : Check Member SSH"
echo -e "> userlimit    : Limit login Dropbear"
echo -e "> userlimitssh : Limit login SSHD"
echo -e "> resvis       : Restart service dropbear, webmin"
echo -e "                 squid3, OpenVPN dan SSH"
echo -e "> reboot       : Reboot VPS"
echo -e "> speedtest    : Speedtest VPS"
echo -e "> info         : System Information"
echo -e "> about        : About AutoScript"
echo -e "> exit         : Exit terminal SSH"
echo -e ""
echo -e "================================================="
